### ISSUE TITLE
Go modules

### ISSUE THREAD

**Issue by ddevault** [alexbakker/go-wlroots#1]
Would be nice if this supported Go modules instead of being a legacy-style project

**Comment by alexbakker** [comment]
Using go-wlroots with Go modules should work without any changes. What specifically doesn't work for you?

**Comment by ddevault** [comment]
Sorry, my mistake. After some finageling I got it to work.

**Comment by alexbakker** [comment]
No worries.

**Comment by ddevault** [comment]
Taking another look at this. The following doesn't work:

```
$ git clone https://github.com/swaywm/go-wlroots
$ cd go-wlroots
$ go build cmd/tinywl/main.go
cmd/tinywl/main.go:10:2: cannot find package "github.com/swaywm/go-wlroots/wlroots" in any of:
        /usr/lib/go/src/github.com/swaywm/go-wlroots/wlroots (from $GOROOT)
        /home/sircmpwn/.local/share/go/src/github.com/swaywm/go-wlroots/wlroots (from $GOPATH)
```

If I `touch go.mod` I get a little further:

```
# github.com/swaywm/go-wlroots/wlroots
In file included from _cgo_export.c:4:
log.go: In function ‘_wlr_log_inner_cb’:
log.go:14:3: warning: implicit declaration of function ‘vasprintf’; did you mean ‘vsprintf’? [-Wimplicit-function-declaration]
# command-line-arguments
cmd/tinywl/main.go:35:17: undefined: NewServer
```

**Comment by alexbakker** [comment]
Setting ``GO111MODULE=on`` will make ``go`` create a ``go.mod`` file automatically if needed. That said, I've pushed a commit that adds it.

I would advise using the Makefile to build this. With ``go build cmd/tinywl/main.go``, you're only building main.go, but there are other .go files that should also be included. The correct command would be ``go build github.com/swaywm/go-wlroots/cmd/tinywl``

**Comment by ddevault** [comment]
Sweet, thanks! That works.
