### ISSUE TITLE
Incompatible to wlroots 0.6

### ISSUE THREAD

**Issue by Mimoja** [alexbakker/go-wlroots#6]
Quoting the official release notes:

```
To migrate from the old API to the new one:

    Replace wlr_output_make_current calls with wlr_output_attach_render
    Replace wlr_output_swap_buffers calls with wlr_output_set_damage and wlr_output_commit
    Replace wlr_output_damage_make_current calls with wlr_output_damage_attach_render
    Replace wlr_output_damage_swap_buffers with wlr_output_set_damage and wlr_output_commit
    Replace wlr_output.needs_swap with wlr_output.needs_frame
    Replace wlr_output.events.swap_buffers with wlr_output.events.precommit

```

This applies at least to 
- func (o Output) MakeCurrent() (int, error) (output.go:68)
- func (o Output) SwapBuffers()  (output.go:84)

and maybe some others.

**Comment by alexbakker** [comment]
Thanks for letting me know. I haven't been keeping track of wlroots development lately. I applied the API changes locally, but I'm also running into the following errors:

```
wlroots/wlroots.go:20:33: p.events undefined (type *_Ctype_struct_wlr_backend has no field or method events)
wlroots/wlroots.go:29:35: b.p.events undefined (type *_Ctype_struct_wlr_backend has no field or method events)
wlroots/wlroots.go:43:35: b.p.events undefined (type *_Ctype_struct_wlr_backend has no field or method events)
wlroots/wlroots.go:51:35: b.p.events undefined (type *_Ctype_struct_wlr_backend has no field or method events)
make: *** [Makefile:6: tinywl] Error 2
```

I'll take a closer look tonight.

**Comment by Mimoja** [comment]
It appears to be a 0.6.0 specific problem, that the event structs are now no longer found by cgo. This might be due to the struct now beeing packed(?) / padded in a different way, so that go does no longer support it. Support for 0.5.0 was trivial to implement yesterday...

**Comment by Mimoja** [comment]
I am currently using this commit:
https://github.com/Mimoja/go-wlroots/commit/f82881531c56f27e68fad2ed989f9371aa258115
If you think it makes sense, feel free to merge :)
PR #7

**Comment by alexbakker** [comment]
It's strange, because the ``wlr_backend`` struct in ``wlr/backend.h`` file has not changed since October 2018. Perhaps some behavior of cgo changed in the latest version of Go.

**Comment by Mimoja** [comment]
Not working on Go 1.12 for me

**Comment by alexbakker** [comment]
On a hunch I merged all files in the ``wlroots`` package into a single Go file and now it compiles just fine on 0.6.0. This looks like a Cgo bug to me.
