### ISSUE TITLE
Using channels instead of callbacks

### ISSUE THREAD

**Issue by yotamN** [alexbakker/go-wlroots#8]
It would be a more idiomatic API to use channels to pass events like OnNewInput and OnNewOutput. I'm not 100% sure how to would be implemented but it should probably be function that return a channel and the function itself will register a callback, something like that:

```
func (b Backend) NewOutputChan() chan Output {
	var c chan Output
	b.OnNewOutput(func(o Output) {
		c <- o
	})
	return c
}
```

**Comment by dominikh** [comment]
As described, this will not work correctly for some (all?) events. Take the output's frame event, for example: rendering has to happen inside the callback. However, with your example, the callback is over as soon as the channel send has succeeded, before actual rendering occurs. So at the least, there would need to be two-way signaling, which isn't exactly pretty.

Another minor nit would be the fact that your function should accept a channel, not return one. And finally, assuming the fundamental issue didn't exist, the existing API already allows you to send to channels in your callbacks, which means you could trivially implement this yourself, without the code having to exist in the wlroots bindings.

**Comment by alexbakker** [comment]
I don't actively work on this project anymore and must have missed this issue. Aside from the issues described by @dominikh, I don't think this is idiomatic Go.
