### ISSUE TITLE
build error: too many arguments in call to _Cfunc_wlr_output_commit

### ISSUE THREAD

**Issue by mewmew** [alexbakker/go-wlroots#9]
Hi @alexbakker,

My friend and I just came across go-wlroots today, and we just wanted to say we are quite impressed with what you've managed to implement thus far. It is really exciting to see a bare bones Wayland compositor implemented in Go, that is still useful.

When we tried to build the project, we ran into a minor build error (at rev e84b42aef57702e9bbe006ea070387c06889c464):

```
# github.com/swaywm/go-wlroots/wlroots
wlroots/wlroots.go:754:21: too many arguments in call to _Cfunc_wlr_output_commit
	have (*_Ctype_struct_wlr_output, nil, nil)
	want (*_Ctype_struct_wlr_output)
wlroots/wlroots.go:814:19: m.p.flags undefined (type *_Ctype_struct_wlr_output_mode has no field or method flags)
make: *** [Makefile:6: tinywl] Error 2
```

I have wlroots v0.7.0 installed.

```
$ pacman -Q wlroots
wlroots 0.7.0-1
```

Wish you a really lovely start of the autumn and can't state how excited I am to have found this project of yours!

Cheerful regards,
Robin & Daniel

**Comment by alexbakker** [comment]
Thansk for the patch and the kind words!
